name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for GitHub Pages
        run: npm run build:gh-pages

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Create GitHub Pages repository root
        run: |
          # Create directory structure for GitHub Pages
          mkdir -p ./gh-pages-root/Schedule-Swap/swap
          
          # Copy the built files to the swap subdirectory
          cp -r ./dist/* ./gh-pages-root/Schedule-Swap/swap/
          
          # Create a redirect at the root
          cat > ./gh-pages-root/index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Schedule Swap</title>
              <meta http-equiv="refresh" content="0;url=./Schedule-Swap/swap/" />
            </head>
            <body>
              Redirecting to application...
            </body>
          </html>
          EOF
          
          # Create a redirect at the repository root
          cat > ./gh-pages-root/Schedule-Swap/index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Schedule Swap</title>
              <meta http-equiv="refresh" content="0;url=./swap/" />
            </head>
            <body>
              Redirecting to application...
            </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './gh-pages-root'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4