name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for GitHub Pages
        run: npm run build:gh-pages

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Setup directory structure for GitHub Pages
        run: |
          # Create swap directory
          mkdir -p ./dist/swap
          
          # Create .nojekyll in swap directory
          touch ./dist/swap/.nojekyll
          
          # Create index.html for swap directory
          cp ./dist/index.html ./dist/swap/index.html
          
          # Copy assets to swap directory
          cp -r ./dist/assets ./dist/swap/
          
          # Create 404.html in both root and swap directory
          cat > ./dist/404.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Schedule Swap</title>
              <script>
                // Store the URL we tried to reach for later redirect
                var pathname = window.location.pathname;
                console.log('404 handler - pathname:', pathname);
                
                // Store the pathname for later use
                sessionStorage.setItem('redirect-path', pathname);
                
                // Determine the correct place to redirect
                var parts = pathname.split('/');
                var repoName = parts[1] || '';
                
                // If this is a GitHub Pages site, build the right path
                if (window.location.hostname.endsWith('github.io') && repoName) {
                  window.location.href = '/' + repoName + '/swap/';
                } else {
                  window.location.href = '/swap/';
                }
              </script>
            </head>
            <body>
              <h1>Page Not Found</h1>
              <p>Redirecting to the application...</p>
            </body>
          </html>
          EOF
          
          # Copy 404.html to swap directory too
          cp ./dist/404.html ./dist/swap/404.html
          
          # Create root index.html with redirect
          cat > ./dist/index.html << EOF
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Schedule Swap</title>
              <script>
                // Get repo name from URL
                var parts = window.location.pathname.split('/');
                var repoName = parts[1] || '';
                
                // Check if we're at the root
                var isRoot = parts.length <= 2 || (parts.length === 3 && !parts[2]);
                
                if (isRoot) {
                  // If on GitHub Pages, redirect to /repo-name/swap/
                  if (window.location.hostname.endsWith('github.io') && repoName) {
                    window.location.href = '/' + repoName + '/swap/';
                  } else {
                    window.location.href = '/swap/';
                  }
                }
              </script>
            </head>
            <body>
              <h1>Schedule Swap</h1>
              <p>Redirecting to application...</p>
            </body>
          </html>
          EOF
          
          # Create CNAME file for custom domain
          echo "adityasood.me" > ./dist/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4